evalVersion = 'fast' ;

models = {...
    'ssd-mcn-pascal-vggvd-300', ...
} ;
    %'ssd-pascal-mobilenet-ft-300' ...

modelOpts.nmsTopK = 400 ;
modelOpts.keepTopK = 200 ;
modelOpts.confThresh = 0.01 ;

for i = 1:numel(models)
    model = models{i} ; args = {} ;
    ssd_pascal_evaluation('modelName', model, ...
                          'year', 2007,  ...
                          'testset', 'test', ...
                          'refreshCache', 1, ...
                          'gpus', 3, ...
                          'modelOpts', modelOpts, ...
                          'evalVersion', evalVersion) ;
end

