evalVersion = 'fast' ;

models = {...
   'ssd-mscoco-vggvd-300', ...
} ;

for i = 1:numel(models)
    model = models{i} ; args = {} ;
    ssd_pascal_evaluation('modelName', model, ...
                          'year', 2012,  ...
                          'testset', 'val', ...
                          'refreshCache', 0, ...
                          'evalVersion', evalVersion, args{:}) ;
end

