ENABLE_GPU := yes
ENABLE_CUDNN := yes
ENABLE_IMREADJPEG := yes
MEXOPTS := matlab/src/config/mex_CUDA_glnxa64.sh

# Configure CUDA and CuDNN. CUDAMETHOD can be either 'nvcc' or 'mex'.
CUDAROOT := /usr/local/cuda
CUDNNROOT := /home/albanie/local/cudnn4
CUDAMETHOD := $(if $(ENABLE_CUDNN),nvcc,mex)
ARCH := glnxa64
MATLABROOT := /opt/matlab
ENABLE_DOUBLE :=  # false
DEBUG := yes

##$(if $(ENABLE_DOUBLE))
##   $(info VAR="enabled")
##else

#ifeq ($(ENABLE_DOUBLE), yes)
#    CXXFLAGS := $(CXXFLAGS) -DENABLE_DOUBLE
#endif
#$(info VAR="$(CXXFLAGS)")

#make ARCH=glnxa64  ENABLE_GPU=yes CUDAROOT=/usr/local/cuda-7.5 CUDAMETHOD=nvcc 
#ENABLE_CUDNN=yes 
#CUDNNROOT=/sync/cudnn/cudnn-v4 
#ENABLE_IMREADJPEG=yes 
#MEXOPTS=matlab/src/config/mex_CUDA_glnxa64.sh
