function net = ssd_zoo(modelName)

caffeModels = {
    'ssd-pascal-vggvd-300', ...
    'ssd-pascal-vggvd-512', ...
    'ssd-pascal-plus-vggvd-300', ...
    'ssd-pascal-vggvd-ft-300', ...
    'ssd-pascal-plus-vggvd-512', ...
    'ssd-pascal-plus-vggvd-ft-300', ...
    'ssd-pascal-plus-vggvd-ft-512', ...
    'ssd-pascal-vggvd-ft-512', ...
} ;
mcnModels = {
    'ssd-mcn-pascal-vggvd-300', ...
} ;

modelNames = horzcat(caffeModels, mcnModels) ;

assert(ismember(modelName, modelNames), 'unrecognised model') ;
modelDir = fullfile(vl_rootnn, 'data/models-import') ;
modelPath = fullfile(modelDir, sprintf('%s.mat', modelName)) ;
net = dagnn.DagNN.loadobj(load(modelPath)) ;
